export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';
export const SET_CURRENT_PRODUCT_LIST = 'SET_CURRENT_PRODUCT_LIST';
export const SET_PRODUCT_WISHLIST = 'SET_PRODUCT_WISHLIST';
export const SET_CURRENT_SORTING = 'SET_CURRENT_SORTING';
export const SET_AVAILABLE_FILTERS = 'SET_AVAILABLE_FILTERS';
export const SET_CURRENT_FILTERS = 'SET_CURRENT_FILTERS';
